default_install_hook_types: [pre-commit, commit-msg]
fail_fast: true
repos:

  # Commit messages + Tests
  - repo: local
    hooks:
      - id: validate-commit-msg
        stages: [commit-msg]
        name: validate-commit-msg
        language: pygrep
        entry: ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(\(\w+\)?((?=:\s)|(?=!:\s)))?(!)?(:\s\_\_.*\_\_)?|^(Merge \w+)
        args: [--negate]
      - id: pytest
        stages: [pre-commit]
        name: pytest
        entry: pytest --cov-report=
        language: system
        pass_filenames: false
        always_run: true

  # Auto-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        pass_filenames: false
        stages: [pre-commit]
      - id: trailing-whitespace
        pass_filenames: false
        stages: [pre-commit]

  # Lint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        stages: [pre-commit]
        name: ruff (lint)
        args:
          - "--output-format=text"
          - "."
        pass_filenames: false

  # Type
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        pass_filenames: false

  # CI Lint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.27.3"
    hooks:
      - id: check-github-workflows
        stages: [pre-commit]
      - id: check-dependabot
        stages: [pre-commit]
