version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install ".[docs]"
    - |
      fgr docs . \
        --index-from-readme \
        --include-private-modules \
        --author dan@1howardcapital.com \
        --version $(fgr --version) \
        --site-map-url https://fgr.readthedocs.io/en/latest
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp -r docs/* $READTHEDOCS_OUTPUT/html/
