name: pr

on: [pull_request]

env:
  PY_VERSIONS: "[\"3.12\",\"3.11\",\"3.10\"]"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.setVariables.outputs.python-versions }}
    steps:
      - id: setVariables
        run: |
          echo "python-versions=${{ toJson(env.PY_VERSIONS) }}" >> $GITHUB_OUTPUT
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Latest
        uses: actions/setup-python@v5
        with:
          python-version: ${{ fromJson(env.PY_VERSIONS)[0] }}
      - name: setup dependencies
        run: |
          python -m pip install ".[develop]"
      - name: ruff
        run: |
          python -m ruff check . \
            --config pyproject.toml \
            --diff \
            --show-source \
            --exit-non-zero-on-fix
  test:
    needs: [setup, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.setup.outputs.python-versions) }}
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup dependencies
        run: |
          python -m pip install ".[develop]"
      - name: mypy
        run: python -m mypy
      - name: pytest
        run: pytest --cov-report=xml
